### ISSUE TITLE
Finished

### ISSUE THREAD

**Issue by jkonowitch** [jkonowitch/Travel.ly#20]
@jkonowitch

**Comment by itorres1** [comment]
Blast from the past..

On Tue, Jun 2, 2015 at 11:45 AM, Jeffrey Konowitch <notifications@github.com

**Comment by mpvazquez** [comment]
So long, Travel.ly http://travel.ly/

Marco Pretell-Vázquez

email: marco.pvazquez@gmail.com mailto:marco.pvazquez@gmail.com
web: marcopvazquez.com http://www.marcopvazquez.com/
cell: 917-972-1184

**Comment by qiheme** [comment]
Nostalgia...

**Comment by jkonowitch** [comment]
:)
